mode: backtest  # live or backtest

broker:
  name: binance
  api_key: "your_api_key"
  api_secret: "your_api_secret"
  testnet: true  # true for testnet, false for live

strategy:
  name: smc_orderblock
  symbol: "BTCUSDT"
  timeframe: "4h"
  position_size: 0.001
  max_positions: 1

backtest:
  start: "2024-08-01"
  end: "2025-08-01"

risk:
  max_daily_loss: 100
  max_trades_per_day: 5
  risk_per_trade_pct: 0.02  # Conservative 2% risk per trade

logging:
  level: INFO
  file: "data/trading.log"

# Conservative realism and anti-overfitting settings:
fee_rate: 0.001        # 0.1% spot fee
slippage_rate: 0.001   # Increased slippage for conservatism
min_order_size: 0.001  # For BTCUSDT
in_sample_pct: 0.7     # 70% for in-sample, 30% for out-of-sample
initial_balance: 10000 # Starting balance

# Conservative enhanced strategy parameters
target_monthly_return: 0.15           # More conservative 15% monthly target
stop_loss_range: [0.015, 0.02, 0.025, 0.03]  # Tighter range, more conservative
take_profit_range: [0.02, 0.025, 0.03, 0.035] # Tighter range
enhanced_backtest: true              # Use enhanced monthly backtesting
walk_forward_optimization: true      # Use walk-forward validation
lookback_months: 6                   # Number of months to use for parameter optimization