mode: backtest  # live or backtest

broker:
  name: binance
  api_key: "your_api_key"
  api_secret: "your_api_secret"
  testnet: true  # true for testnet, false for live

strategy:
  name: smc_orderblock
  symbol: "BTCUSDT"
  timeframe: "4h"
  position_size: 0.001
  max_positions: 1

backtest:
  start: "2024-08-01"
  end: "2025-08-01"

risk:
  max_daily_loss: 100
  max_trades_per_day: 5

logging:
  level: INFO
  file: "data/trading.log"

# Realism and anti-overfitting settings:
fee_rate: 0.001        # 0.1% spot fee; use 0.0004 for futures
slippage_rate: 0.0005  # 0.05% slippage per trade
min_order_size: 0.001  # For BTCUSDT; adjust per symbol
in_sample_pct: 0.7     # 70% for in-sample, 30% for out-of-sample
initial_balance: 10000 # Starting balance
stop_loss_pct: 0.01        # 1% stop loss
take_profit_pct: 0.02      # 2% take profit
imbalance_threshold: 0.0002